const crops = [
    { name: 'Sugarcane', image: '/images/crops/sugarcane.jpg' },
    { name: 'Peanuts', image: '/images/crops/peanuts.jpg' },
    { name: 'Rice', image: '/images/crops/rice.jpg' },
    { name: 'Maize', image: '/images/crops/maize.jpg' },
    { name: 'Carrot', image: '/images/crops/carrot.jpg' },
    { name: 'Bajra', image: '/images/crops/bajra.jpg' },
    { name: 'Barley', image: '/images/crops/barley.jpg' },
    { name: 'Beetroot', image: '/images/crops/beetroot.jpg' },
    { name: 'Coffee', image: '/images/crops/coffee.jpg' },
    { name: 'Corn', image: '/images/crops/corn.jpg' },
    { name: 'Cotton', image: '/images/crops/cotton.jpg' },
    { name: 'Garlic', image: '/images/crops/garlic.jpg' },
    { name: 'Goldwheat', image: '/images/crops/goldwheat.jpg' },
    { name: 'Greenwheat', image: '/images/crops/greenwheat.jpg' },
    { name: 'Jowar', image: '/images/crops/jowar.jpg' },
    { name: 'Linseed', image: '/images/crops/linseed.jpg' },
    { name: 'Mustard', image: '/images/crops/mustard.jpg' },
    { name: 'Onion', image: '/images/crops/onion.jpg' },
    { name: 'Peas', image: '/images/crops/peas.jpg' },
    { name: 'Pineapple', image: '/images/crops/pineapple.jpg' },
    { name: 'Potato', image: '/images/crops/potato.jpg' },
    { name: 'Redbellpeppers', image: '/images/crops/redbellpeppers.jpg' },
    { name: 'Soybean', image: '/images/crops/soybean.jpg' },
    { name: 'Strawberry', image: '/images/crops/strawberry.jpg' },
    { name: 'Sunflower', image: '/images/crops/sunflower.jpg' },
    { name: 'Tomato', image: '/images/crops/tomato.jpg' },
];

export default crops;
