const crops = [
    { name: 'Almond', image: '/images/crops/Almond.jpg' },
    { name: 'Apple', image: '/images/crops/Apple.jpg' },
    { name: 'Apricot', image: '/images/crops/Apricot.jpg' },
    { name: 'Arum', image: '/images/crops/Arum.jpg' },
    { name: 'Bajra', image: '/images/crops/bajra.jpg' },
    { name: 'Banana', image: '/images/crops/Banana.jpg' },
    { name: 'Barley', image: '/images/crops/barley.jpg' },
    { name: 'Beetroot', image: '/images/crops/beetroot.jpg' },
    { name: 'Ber', image: '/images/crops/Ber.jpg' },
    { name: 'Bitter gourd', image: '/images/crops/Bitter Gourd.jpg' },
    { name: 'Bottle gourd', image: '/images/crops/Bottle Gourd.jpg' },
    { name: 'Brinjal', image: '/images/crops/Brinjal.jpg' },
    { name: 'Cabbage', image: '/images/crops/Cabbage.jpg' },
    { name: 'Carrot', image: '/images/crops/carrot.jpg' },
    { name: 'Cauliflower', image: '/images/crops/Cauliflower.jpg' },
    { name: 'Chikoo', image: '/images/crops/Chikoo.jpg' },
    { name: 'Coconut', image: '/images/crops/Coconut.jpg' },
    { name: 'Coffee', image: '/images/crops/coffee.jpg' },
    { name: 'Corn', image: '/images/crops/corn.jpg' },
    { name: 'Corriander', image: '/images/crops/Corriander.jpg' },
    { name: 'Cotton', image: '/images/crops/cotton.jpg' },
    { name: 'Cucumber', image: '/images/crops/Cucumber.jpg' },
    { name: 'Dates', image: '/images/crops/Dates.jpg' },
    { name: 'Falsa', image: '/images/crops/Falsa.jpg' },
    { name: 'Figs', image: '/images/crops/Figs.jpg' },
    { name: 'Garlic', image: '/images/crops/garlic.jpg' },
    { name: 'Goldwheat', image: '/images/crops/goldwheat.jpg' },
    { name: 'Grapefruit', image: '/images/crops/Grapefruit.jpg' },
    { name: 'Green grapes', image: '/images/crops/Green Grapes.jpg' },
    { name: 'Greenwheat', image: '/images/crops/greenwheat.jpg' },
    { name: 'Guava', image: '/images/crops/Guava.jpg' },
    { name: 'Jowar', image: '/images/crops/jowar.jpg' },
    { name: 'Lemon', image: '/images/crops/Lemon.jpg' },
    { name: 'Lettuce', image: '/images/crops/Lettuce.jpg' },
    { name: 'Lichi', image: '/images/crops/Lichi.jpg' },
    { name: 'Linseed', image: '/images/crops/linseed.jpg' },
    { name: 'Long melon', image: '/images/crops/Long Melon.jpg' },
    { name: 'Loquat', image: '/images/crops/Loquat.jpg' },
    { name: 'Luffa', image: '/images/crops/Luffa.jpg' },
    { name: 'Maize', image: '/images/crops/maize.jpg' },
    { name: 'Mandarine', image: '/images/crops/Mandarine.jpg' },
    { name: 'Mango', image: '/images/crops/Mango.jpg' },
    { name: 'Masoor', image: '/images/crops/Masoor.jpg' },
    { name: 'Mulberry', image: '/images/crops/Mulberry.jpg' },
    { name: 'Mung', image: '/images/crops/Mung.jpg' },
    { name: 'Musk melon', image: '/images/crops/Musk Melon.jpg' },
    { name: 'Mustard', image: '/images/crops/mustard.jpg' },
    { name: 'Musubi', image: '/images/crops/Musubi.jpg' },
    { name: 'Onion', image: '/images/crops/onion.jpg' },
    { name: 'Orange', image: '/images/crops/Orange.jpg' },
    { name: 'Papaya', image: '/images/crops/Papaya.jpg' },
    { name: 'Peaches', image: '/images/crops/Peaches.jpg' },
    { name: 'Peanuts', image: '/images/crops/peanuts.jpg' },
    { name: 'Pear', image: '/images/crops/Pear.jpg' },
    { name: 'Peas', image: '/images/crops/peas.jpg' },
    { name: 'Pineapple', image: '/images/crops/pineapple.jpg' },
    { name: 'Plums', image: '/images/crops/Plums.jpg' },
    { name: 'Pomegrante', image: '/images/crops/Pomegrante.jpg' },
    { name: 'Potato', image: '/images/crops/potato.jpg' },
    { name: 'Pumpkin', image: '/images/crops/Pumpkin.jpg' },
    { name: 'Radish', image: '/images/crops/Radish.jpg' },
    { name: 'Red chilli', image: '/images/crops/Red Chilli.jpg' },
    { name: 'Red grapes', image: '/images/crops/Red Grapes.jpg' },
    { name: 'Redbellpeppers', image: '/images/crops/redbellpeppers.jpg' },
    { name: 'Rice', image: '/images/crops/rice.jpg' },
    { name: 'Safflower', image: '/images/crops/Safflower.jpg' },
    { name: 'Seasamum', image: '/images/crops/Seasamum.jpg' },
    { name: 'Sour lime', image: '/images/crops/Sour Lime.jpg' },
    { name: 'Sour orange', image: '/images/crops/Sour Orange.jpg' },
    { name: 'Soyabean', image: '/images/crops/Soyabean.jpg' },
    { name: 'Soybean', image: '/images/crops/soybean.jpg' },
    { name: 'Spinach', image: '/images/crops/Spinach.jpg' },
    { name: 'Strawberry', image: '/images/crops/strawberry.jpg' },
    { name: 'Sugarcane', image: '/images/crops/sugarcane.jpg' },
    { name: 'Sunflower', image: '/images/crops/sunflower.jpg' },
    { name: 'Sweet lime', image: '/images/crops/Sweet Lime.jpg' },
    { name: 'Sweet potato', image: '/images/crops/Sweet Potato.jpg' },
    { name: 'Tobacco', image: '/images/crops/Tobacco.jpg' },
    { name: 'Tomato', image: '/images/crops/tomato.jpg' },
    { name: 'Turmeric', image: '/images/crops/Turmeric.jpg' },
    { name: 'Turnip', image: '/images/crops/Turnip.jpg' },
    { name: 'Walnut', image: '/images/crops/Walnut.jpg' },
    { name: 'Watermelon', image: '/images/crops/Watermelon.jpg' },
    { name: 'Wheat', image: '/images/crops/Wheat.jpg' },
];

export default crops;
